[book]
authors = ["Suyog Tandel"]
language = "en"
multilingual = false
src = "src"
title = "Setting Up Rust on Windows: The Visual Studio-Free Path"

[output.html.playground]
runnable = false

[output.html]
git-repository-url = "https://github.com/RedddFoxxyy/rust_no_vs_setup_guide"
